<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-6Q5KS8MJ" name="Demo.ClassE" tests="3" failures="1" timestamp="2021-06-10T11:39:22 IST" time="530.250" errors="0">
  <testcase name="verifySignpuWithFreePlusPaidBluetoothDevice" time="335.898" classname="Demo.ClassE"/>
  <testcase name="verifySignupWithFreeBluetoothDevice" time="105.674" classname="Demo.ClassE"/>
  <testcase name="verifyActivateCellularDeviceWhichContainNoInvoiceUnderFreeBluetoothAccount" time="88.678" classname="Demo.ClassE">
    <failure type="java.lang.AssertionError" message="500 (Internal Server Error) did not expect to find [false] but found [true]">
      <![CDATA[java.lang.AssertionError: 500 (Internal Server Error) did not expect to find [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertFalse(Assert.java:65)
at com.autobrain.base.Signup.signup(Signup.java:160)
at com.autobrain.pages.SignupWithBluetoothDevice.signupWithBluetoothDevice(SignupWithBluetoothDevice.java:24)
at Demo.ClassE.verifyActivateCellularDeviceWhichContainNoInvoiceUnderFreeBluetoothAccount(ClassE.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- verifyActivateCellularDeviceWhichContainNoInvoiceUnderFreeBluetoothAccount -->
</testsuite> <!-- Demo.ClassE -->
